---
title: "RWorksheet_Tubat#4a"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r number1}
#1. 
shoeSize = c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,7.5,10.5,8.5,12.0,10.5,13.0,11.5,8.5,5.0,10.0,6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,13.0)
height = c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0,77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0,69.0,70.0)
gender = c("F", "F", "F", "F", "M", "F","F","F","M","F","M","F", "M", "M", "M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M")
length(shoeSize)
df <- data.frame(shoeSize, height, gender)
colnames(df) <- c("Shoe Size", "Height", "Gender")




```

```{r}
#1a.
dim(df)
#The data set has 28 rows and 3 columns
```

```{r}
#1b. 
#Created a data where the male and the female is separated
males <- df[df$Gender == "M", ]
males
females <- df[df$Gender == "F", ]
females

```

```{r}
#1c. 
mean(df$Height)
mean(df$`Shoe Size`)
```

```{r }
#1d.
#Yes, there is a relationship between the shoe size and the height of the height. The taller the height, the bigger the shoe size. 
```


```{r number2}
months_vector <- c("March","April","January","November","January","September","October","September","November","August", "January","November","November","February","May","August", "July","December","August","August","September","November","February", "April")
factor_months_vector <- factor(months_vector)
factor_months_vector
```

```{r number3}
summary(months_vector)
summary(factor_months_vector)
#The summary of the months_vector consists of the number of elements in the vector, the class, and the mode of the vector which is the character data type. 
#In the summary of the factor_months_vector it lists all the elements and then it counts the number of times the element shows up inside the vector.
```
```{r number 4}
direction <- c("East", "West", "North")
frequency <- c(1,4,3)
factor_data <- c("East", "West", "North", 1, 4, 3)
factor_data
new_order_data <- factor(factor_data, levels = c("East","West", "North"))
print(new_order_data)

```
```{r number 5}
#5a. 
library(readxl)
df2 <- read.table(file ="/cloud/project/worksheet#4/import_march.csv", sep= ",",header=TRUE,as.is=TRUE)
df2


```

```{r}
#5b. 
df2
```


```{r number6}

numberInput <- readline(prompt="Enter a number from 1 to 50: ")
initBool = FALSE;
if(numberInput == 20){
  cat("TRUE")
}else if(numberInput >= 1 && numberInput <= 50){
  cat("Your number is", numberInput)
}else{
  cat("The number selected is beyond the range of 1 to 50")
}

```

```{r number7}
price <- as.integer(readline(prompt = "Enter a number here: "))
bills1000 <- price %/% 1000
price %% 1000
bills500 <- price %/% 500
price <- price %% 500
bills200 = price %/% 200
price <- price %% 200
bills100 = price %/% 100
price <- price %% 100
bills50 <- price %/% 50


minimumBills <- bills1000 + bills500 + bills200 + bills100 + bills50
cat("1000 bill: ",bills1000)
cat("500 bill: ",bills500)
cat("200 bill: ",bills200)
cat("100 bill: ",bills100)
cat("50 bill: ",bills50)
cat("minimum bills: ", minimumBills)


```



```{r number8ab}
name <- c("Annie", "Thea", "Steve", "Hanna")
grade1 <- c(85, 65, 75,95)
grade2 <- c(65,75,55,75)
grade3 <- c(85,90,80,100)
grade4 <- c(100,90,85,90)

dfNum8 <- data.frame(name, grade1, grade2, grade3, grade4)
colnames(dfNum8) <- c("Name", "Grade1", "Grade2", "Grade3", "Grade4")

dfNum8$AverageScore <- (dfNum8$Grade1 + dfNum8$Grade2 + dfNum8$Grade3 + dfNum8$Grade4) / 4

highAverage <- dfNum8[dfNum8$AverageScore > 90, ]


for (i in 1:nrow(highAverage)) {
  cat(paste(highAverage$Name[i], "'s average grade this semester is ", highAverage$AverageScore[i], ".\n"))
#No output because no-one has an average greater than 90.
}


```
```{r number8c}
averageTest <- c("Average Test", sum(dfNum8$Grade1)/4,sum(dfNum8$Grade2)/4, sum(dfNum8$Grade3)/4, sum(dfNum8$Grade4)/4)
lowScore <- which(averageTest < 80)

for(i in lowScore){
  cat("",i-1,"is difficult\n")
}

```
```{r number8d}
for (i in 1:nrow(dfNum8)) {
  student <- dfNum8$Name[i]
  grades <- dfNum8[i, 2:5]
  highest_grade <- grades[i]
  for (j in 2:4) {
    if (grades[j] > highest_grade) {
      highest_grade <- grades[j]
    }
  }
  
  if (highest_grade > 90) {
    cat(paste(student, "'s highest grade this semester is ", highest_grade, ".\n"))
  }
}

```
















